### ISSUE TITLE
Provide documentation for server

### ISSUE THREAD

**Issue by mateuszlewko** [pubsubsql/pubsubsql#67]
There is no documentation regarding how to configure and setup service.
Can I connect it to my existing MySql database? 
Can I use it as a normal database (so my app that connects to mysql db would work without any changes)? 

The project looks awesome but without proper documentation others can't user and possibly contribute.

**Comment by marinbek** [comment]
Hi,

check the homepage, documentation for starting the server is here - http://pubsubsql.com/getting-started and you also have client documentation under "Docs" on the homepage.

You can connect it to an existing database but you cannot use it by simply replacing the connector - it is incompatible at the moment so you would have to modify your code.
