### ISSUE TITLE
Throughput control

### ISSUE THREAD

**Issue by fimmugit** [pubsubsql/pubsubsql#69]
I am using pubsubsql to update a UI with time-sensitive stock data. I am wondering if there is a way to adjust the rate of data pushed so that the subscriber is able to process all incoming data without getting jammed?

**Comment by marinbek** [comment]
Rate limiting isn't implemented at the moment and isn't on the roadmap. If you happen to implemented we will happily merge it or we can add it to backlog.

**Comment by fimmugit** [comment]
Hi, Thanks for the response. I got another question for you. Do you have any idea how many concurrent subscribers can pubsubsql server support?
    On Monday, October 2, 2017, 1:03:42 PM EDT, Marin Bek <notifications@github.com> wrote:  
 
 
Rate limiting isn't implemented at the moment and isn't on the roadmap. If you happen to implemented we will happily merge it or we can add it to backlog.
